from src.utils import R, C, logger, create_embed, error_embed, get_log_channel
import discord


class RoleSelectView(discord.ui.View):
    def __init__(self):
        super().__init__(timeout=180)
        self.selected_roles: list[discord.Role] = []

    @discord.ui.role_select(
        placeholder=R.team_list_role_select_placeholder,
        min_values=1,
        max_values=25,
        custom_id="role_select_dropdown"
    )
    async def select_callback(self, select: discord.ui.Select, interaction: discord.Interaction):
        self.selected_roles = select.values
        # Acknowledge the interaction to prevent "Interaction failed"
        await interaction.response.defer()

    @discord.ui.button(
        label=R.team_list_submit_button_label,
        style=discord.ButtonStyle.primary,
        custom_id="submit_roles"
    )
    async def submit_callback(self, button, interaction: discord.Interaction):
        if not self.selected_roles:
            await interaction.response.send_message(embed=create_embed(R.team_list_select_at_least_one_role, color=C.error_color), ephemeral=True)
            return
        await interaction.response.defer()

        embed = discord.Embed(
            title=R.team_list_embed_title, color=C.embed_color)

        # Sort selected roles by position (highest first)
        sorted_selected_roles = sorted(
            self.selected_roles, key=lambda r: r.position, reverse=True)

        # Create a mapping of members to their highest role
        sorted_role_member_map: dict[discord.Role, list[discord.Member]] = {}
        assigned_members = []
        for role in sorted_selected_roles:
            sorted_role_member_map[role] = []
            for member in role.members:
                if member not in assigned_members:
                    assigned_members.append(member)
                    sorted_role_member_map[role].append(member)

        # Create embed
        for (role, members) in sorted_role_member_map.items():
            title = f"**{role.mention} ({len(members)})**"
            if len(members) > 0:
                text = "\n".join(
                    [f"- {member.mention} ({member.name})" for member in members])
                embed.add_field(
                    name="",
                    value=f"{title}\n{text}",
                    inline=False
                )
            else:
                embed.add_field(
                    name="",
                    value=f"{title}\n{R.team_list_no_members_found}",
                    inline=False
                )

        await interaction.channel.send(embed=embed)

        logger.info(
            "team", f"Showing team list for roles: {', '.join([r.name for r in sorted_selected_roles])}")
        logger.info(
            "team", f"Team list generated by {interaction.user.name} (ID: {interaction.user.id})")

        self.stop()  # Stop the view after submission


def setup_team_list_command(bot: discord.Bot):
    team = discord.SlashCommandGroup(
        "team",
        R.team_group_desc,
        default_member_permissions=discord.Permissions(administrator=True)
    )

    @team.command(name="add", description=R.team_add_desc)
    @discord.default_permissions(administrator=True)
    @discord.option(
        "user",
        description=R.team_add_user_desc,
        type=discord.SlashCommandOptionType.user,
        required=True
    )
    @discord.option(
        "role",
        description=R.team_add_role_desc,
        type=discord.SlashCommandOptionType.role,
        required=True
    )
    async def team_add(ctx: discord.ApplicationContext, user: discord.Member, role: discord.Role):
        log_channel, err = await get_log_channel(ctx.interaction)
        if err:
            await ctx.respond(embed=error_embed(err), ephemeral=True)
            return

        try:
            # Add the role to the user
            await user.add_roles(role, reason=f"Added to team by {ctx.author.name}")
            # Send a message to the log channel
            log_message = R.team_add_success_log % (
                user.mention, ctx.author.mention, role.mention)
            await log_channel.send(embed=create_embed(log_message, title=R.new_team_member_title))
            # Send a confirmation message to the user
            await ctx.respond(embed=create_embed(log_message, color=C.success_color), ephemeral=True)
            logger.info(
                "team", f"{ctx.author.name} added role {role.name} to {user.name}")

        except discord.Forbidden:
            await ctx.respond(embed=error_embed(R.add_role_no_perm), ephemeral=True)
        except discord.HTTPException as e:
            await ctx.respond(embed=error_embed(R.error_occurred % e), ephemeral=True)
            logger.error("team", f"Error adding role: {e}")

    @team.command(name="list", description=R.team_list_desc)
    @discord.default_permissions(administrator=True)
    async def team_list(ctx: discord.ApplicationContext):
        view = RoleSelectView()
        await ctx.respond(embed=create_embed(R.team_list_select_roles_prompt), view=view, ephemeral=True)

    bot.add_application_command(team)
